# Generated by Django 5.0.1 on 2024-07-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionaluserdata',
            old_name='is_organiser',
            new_name='is_organizer',
        ),
    ]
